[features]
seeds = false
skip-lint = false
[programs.devnet]
ecoblocks = "Dvufj2n9dYtimtH8su9ZNHoJ33Yd9a49KAtn5PoJGh2c"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/aashish/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"